{{- if and (not .Values.admin.existingSecret) (or .Values.admin.password .Values.admin.setupToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubedactyl.secretName" . }}
  labels:
    {{- include "kubedactyl.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.admin.password }}
  admin-password: {{ . | quote }}
  {{- end }}
  {{- with .Values.admin.setupToken }}
  setup-token: {{ . | quote }}
  {{- end }}
{{- end }}
