apiVersion: v2
name: kubedactyl
description: Game server panel for Kubernetes that runs Pterodactyl and Pelican eggs as pods.
type: application
version: 0.2.59
appVersion: "0.2.59"
keywords: [game-server, panel, kubernetes, eggs]
home: https://github.com/Syntax3rror404/kubedactyl
sources:
  - https://github.com/Syntax3rror404/kubedactyl
