/** React Query cache keys; invalidating a prefix (e.g. ["servers", server]) refreshes everything below it. */
export const keys = {
  me: ["me"] as const,
  setup: ["setup"] as const,
  legal: ["legal"] as const,
  branding: ["branding"] as const,
  licenses: ["licenses"] as const,
  info: ["info"] as const,
  liveInfo: ["info", "live"] as const,
  tokens: ["me", "tokens"] as const,
  users: ["users"] as const,
  invites: ["invites"] as const,
  invite: (token: string) => ["invite", token] as const,
  cluster: ["cluster"] as const,
  clusterNodes: ["cluster", "nodes"] as const,
  clusterIdentity: ["cluster", "identity"] as const,
  clusterHealth: ["cluster", "health"] as const,
  settings: ["settings"] as const,
  upgrade: ["upgrade"] as const,
  versions: ["versions"] as const,
  requestRates: ["request-rates"] as const,
  storageClasses: ["settings", "storage-classes"] as const,
  pools: ["settings", "pools"] as const,
  eggs: ["eggs"] as const,
  egg: (name: string) => ["eggs", name] as const,
  eggExport: (name: string, format: string) => ["eggs", name, "export", format] as const,
  library: ["egg-library"] as const,
  libraryEgg: (repository: string, path: string) => ["egg-library", repository, path] as const,
  servers: ["servers"] as const,
  server: (server: string) => ["servers", server] as const,
  serverStats: (server: string) => ["servers", server, "stats"] as const,
  serverDiagnostics: (server: string) => ["servers", server, "diagnostics"] as const,
  schedules: (server: string) => ["servers", server, "schedules"] as const,
  backups: (server: string) => ["servers", server, "backups"] as const,
  jobs: (server: string) => ["servers", server, "jobs"] as const,
  /** Listings and contents of a server's files (the session keys are separate). */
  allFiles: (server: string) => ["servers", server, "files"] as const,
  files: (server: string, dir: string) => ["servers", server, "files", "list", dir] as const,
  fileContent: (server: string, file: string) => ["servers", server, "files", "content", file] as const,
  filesOpen: (server: string) => ["servers", server, "files-open"] as const,
  filesSession: (server: string) => ["servers", server, "files-session"] as const,
  filesPodState: (server: string) => ["servers", server, "files-pod-state"] as const,
}
